### ISSUE TITLE
Debugger can't stop at breakpoint at window

### ISSUE THREAD

**Issue by GameEssa** [elixir-lsp/vscode-elixir-ls#158] opened 2020-12-17 14:03 UTC
launch.json
 {
            "type": "mix_task",
            "name": "mix run",
            "task": "run",
            "taskArgs": [
                "--no-halt"
            ],
            "request": "launch",
            "projectDir": "${workspaceRoot}"
        }

I set a breakpoint  in Application .ex,then debug it doesn't stop

**Comment by GameEssa** [comment] 2020-12-17 14:05
IDE: Visual Code 
OS: Window
Elixir: 1.11
Erlang: OTP21

**Comment by lukaszsamson** [comment] 2021-01-06 15:07
@GameEssa please post a minimal repo that reproduces this issue.

**Comment by lukaszsamson** [comment] 2021-12-25 11:08
Closing due to no responce from OP

**Closed by lukaszsamson** 2021-12-25 11:08 UTC

**Comment by dimpdash** [comment] 2022-09-14 12:48
I'm experiencing this issue. when I add a breakpoint and enter a command in the DEBUG CONSOLE I get an error:

"debugged process #PID<0.179.0> exited with reason no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started"

![image](https://user-images.githubusercontent.com/20607550/190157778-bffbe95a-b75c-4033-a560-905bf192a2ee.png)
However when starting the debugging breakpoints work.

The log points in vscode seem to still work though.

I've tried windows and wsl and both have the same issue.

Tested on this sample repo here
https://github.com/BrooklinJazz/debugging_elixir
