### ISSUE TITLE
Umbrella test/build tasks path output isn't highlighted

### ISSUE THREAD

**Issue by mojidabckuu** [elixir-lsp/vscode-elixir-ls#90] opened 2020-05-06 13:37 UTC
Hey, thanks for the great editor support for elixir!

I faced with some UI missing feature. So straight to the details. If you have a simple non umbrella project then paths are relative to the project's root which is totally fine to hover and click on the path. But if you have an umbrella app then task output is relative to the application running the test, so you can't hover and click the path to open. Seems it comes from [fileLocation](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) in problem matcher(not 100% sure). Rapidly checking the doc didn't give me an insight how to handle this. And googling didn't give me the answer on "is it possible to show stacktrace with absolute paths?" 

So the question now it is possible at all?

**Comment by jayjun** [comment] 2020-06-06 15:57
![link](https://user-images.githubusercontent.com/4433966/83948141-ea980180-a84d-11ea-8862-153581bf431f.gif)

Unable to reproduce. Running `mix test` directly in the integrated terminal creates clickable file links too.

Either way, this extension is not involved with file links in the integrated terminal at all. The relevant VS Code issue is https://github.com/microsoft/vscode/issues/69403. You might want to file a bug there.

Also, `fileLocation` creates links in the Problems panel, not task output itself. Add
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "problemMatcher": "$mixTestFailure"
    }
  ]
}
```
to your test task and you can jump to files there.

**Comment by mojidabckuu** [comment] 2020-06-07 05:49
@jayjun It works with test file location. That's true. But what it displays the stack trace then the stacktrace is relative to application not the root project itself. By any change is it possible to add match prefixes or something to hover, highlight and jump at least for project's files? 
Thanks

**Comment by jayjun** [comment] 2020-06-07 06:12
I see what you mean. We can support this when https://github.com/microsoft/vscode/issues/91290 lands.

**Comment by lukaszsamson** [comment] 2020-09-30 16:42
The upstream issue has been resolved

**Comment by axelson** [comment] 2020-11-08 20:58
Now that #148 is merged this is now unblocked.

**Comment by jayjun** [comment] 2020-11-09 15:54
@axelson I’m looking into it. Linking stack trace to files is not straightforward with multiple workspace roots. Also identifying which lines are from dependencies, some likely without source, for example Elixir core libraries.

**Closed** 2020-11-15 19:02 UTC
