### ISSUE TITLE
VSCode it keeps telling me: Could not find Hex

### ISSUE THREAD

**Issue by formingform** [elixir-lsp/vscode-elixir-ls#393] opened 2023-11-27 10:55 UTC
### Environment

Elixir & Erlang versions (elixir --version): 1.14.4 (compiled with Erlang/OTP 25)
VSCode ElixirLS version:
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.133.1-microsoft-standard-WSL2
Operating System Version: Ubuntu 22.04 in WINDOWS 11 WLS2

My project source code locate in d:/github.com/blockscout/blockscout on WINDOWS 11.

### Troubleshooting

> ==> language_server
Could not find Hex, which is needed to build dependency :stream_data
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
Mix.install failed with ** (Mix.Error) request timed out after 60000ms

> Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.

> Alternatively, you can compile and install Hex directly with this command:

>    mix archive.install github hexpm/hex branch latest

>    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/local.ex:145: Mix.Local.find_matching_versions_from_signed_csv!/3
    (mix 1.14.4) lib/mix/tasks/local.hex.ex:72: Mix.Tasks.Local.Hex.run_install/2
    (mix 1.14.4) lib/mix/dep/loader.ex:187: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.4) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.4) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
 

So, I quit VSCode, and run: mix archive.install github hexpm/hex branch latest

> $ mix archive.install github hexpm/hex branch latest

> \* Getting new package (https://github.com/hexpm/hex.git - origin/latest)
remote: Enumerating objects: 13716, done.
remote: Counting objects: 100% (1171/1171), done.
remote: Compressing objects: 100% (601/601), done.
remote: Total 13716 (delta 707), reused 907 (delta 520), pack-reused 12545
All dependencies are up to date
Compiling 1 file (.xrl)
Compiling 14 files (.erl)
Compiling 81 files (.ex)
warning: Mix.ensure_application!/1 is undefined or private
  lib/hex/stdlib.ex:17: Hex.Stdlib.ssh_hostkey_fingerprint/2

> Generated hex app
Generated archive "hex-2.0.6.ez" with MIX_ENV=prod
Found existing entry: /home/joey/.mix/archives/hex-2.0.6
Are you sure you want to replace it with "hex-2.0.6.ez"? [Yn] y
> \* creating /home/joey/.mix/archives/hex-2.0.6

But when I open VSCode, it still tell me: Could not find Hex.

**Comment by lukaszsamson** [comment] 2023-11-28 08:30
Duplicate of https://github.com/elixir-lsp/vscode-elixir-ls/issues/392

**Closed by lukaszsamson** 2023-11-28 08:30 UTC
