### ISSUE TITLE
Error during building the project "file name too long"

### ISSUE THREAD

**Issue by valentyn-yakovlev** [elixir-lsp/vscode-elixir-ls#325] opened 2023-04-25 14:12 UTC
### Repo
https://github.com/elixir-lsp/elixir-ls
master branch
### Environment
elixir
 *1.13.4-otp-25
erlang
 *25.2
both installed via asdf

OS: Ubuntu 22.04
ext4 file system

### Crash report
MIX_ENV=prod mix compile

```
==> erlex
Compiling 1 file (.yrl)
src/parser.yrl: Warning: conflicts: 27 shift/reduce, 0 reduce/reduce
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 1 file (.ex)
Generated erlex app
==> dialyxir_vendored
Compiling 64 files (.ex)
Generated dialyxir_vendored app
==> elixir_ls_utils
Compiling 7 files (.ex)
Generated elixir_ls_utils app
==> elixir_ls_debugger
Compiling 12 files (.ex)
Generated elixir_ls_debugger app
==> language_server
Compiling 235 files (.ex)

17:03:38.726 [error] [label: {:erl_prim_loader, :file_error}, report: 'File operation error: enametoolong. Target: /home/user/myProjects/vscode-elixir-ls/elixir-ls/_build/shared/lib/language_server/ebin/Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent.beam. Function: get_file. Process: code_server.']
```

```
** (File.Error) could not write to file "/home/user/myProjects/vscode-elixir-ls/elixir-ls/_build/shared/lib/language_server/ebin/Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent1.beam": file name too long
    (elixir 1.13.4) lib/file.ex:1054: File.write!/3
    (elixir 1.13.4) lib/kernel/parallel_compiler.ex:246: anonymous fn/3 in Kernel.ParallelCompiler.write_module_binaries/3
    (elixir 1.13.4) lib/enum.ex:1213: anonymous fn/3 in Enum.flat_map/2
    (stdlib 4.2) maps.erl:411: :maps.fold_1/3
    (elixir 1.13.4) lib/enum.ex:2408: Enum.flat_map/2
    (elixir 1.13.4) lib/kernel/parallel_compiler.ex:187: Kernel.ParallelCompiler.spawn_workers/3
    (mix 1.13.4) lib/mix/compilers/elixir.ex:150: Mix.Compilers.Elixir.compile/7
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
```

**Comment by lukaszsamson** [comment] 2023-05-06 08:41
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/832

**Closed by lukaszsamson** 2023-05-06 08:41 UTC
