### ISSUE TITLE
VSCode stops LS after completion on OTP 26 Windows

### ISSUE THREAD

**Issue by mrtkp9993** [elixir-lsp/vscode-elixir-ls#391] opened 2023-11-05 14:17 UTC
After typing `&` character, language-server is crashing.

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

* VSCode ElixirLS version: 0.17.6
* Operating System Version: win32 10.0.22621

### Crash report

1. ElixirLS output:
```
[Error - 5:13:46 PM] Stopping server failed
Error: Stopping the server timed out
    at c:\Users\murat\.vscode\extensions\jakebecker.elixir-ls-0.17.6\out\extension.js:89:9067
```

2. Developer tools errors:
```
notificationsAlerts.ts:42 Client ElixirLS - elixir_gen_alg: connection to server is erroring. Shutting down server.
c @ notificationsAlerts.ts:42
log.ts:441   ERR Model is disposed!: Error: Model is disposed!
    at W.ib (vscode-file://vscode-app/c:/Users/murat/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:728:263)
    at W.getLineCount (vscode-file://vscode-app/c:/Users/murat/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:730:4302)
    at vscode-file://vscode-app/c:/Users/murat/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:31631
```

**Comment by lukaszsamson** [comment] 2023-11-05 15:30
<img width="721" alt="Screenshot 2023-11-05 at 16 27 55" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/f58de557-ca72-46a9-976b-d8c10d03dad5">
I cannot reproduce that. Please share a repo that reproduces the crash. Please attach logs from Output tab https://github.com/elixir-lsp/vscode-elixir-ls#check-elixirls-output

**Comment by mrtkp9993** [comment] 2023-11-05 15:36
It clears Output tab automatically. This is the last output after clearing:

```
[Error - 6:34:15 PM] Stopping server failed
Error: Stopping the server timed out
    at c:\Users\murat\.vscode\extensions\jakebecker.elixir-ls-0.17.6\out\extension.js:89:9067
```

![Recording 2023-11-05 at 18 34 35](https://github.com/elixir-lsp/vscode-elixir-ls/assets/17238910/7c312a9d-696a-48dc-b950-ff53bbd93493)

**Comment by lukaszsamson** [comment] 2023-11-05 22:56
Still cannot reproduce. Please provide more details
<img width="758" alt="Screenshot 2023-11-05 at 23 55 11" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/5bfb7708-dd27-44c2-ba20-43e1eb74074f">
01">

**Comment by infinityfye** [comment] 2023-11-07 21:28
I can confirm a similar behaviour. The only difference in the environment is I'm using ElixirLS `v0.17.7` even the windows version is the same. This happens ONLY on windows, it doesn't happen when running vscode in wsl for example.

For me the LS crashes when typing a map or a struct. To be precise it crashes when typing any character after `%`. If I restart the LS in the middle of the map and finish it it works normally.

I couldn't recreate this behaviour on the `&` character, however.

**Comment by lukaszsamson** [comment] 2023-11-08 05:57
Please downgrade to OTP 25. See details in https://github.com/elixir-lsp/elixir-ls/issues/1023 and OTP bug report https://github.com/erlang/otp/issues/7838

**Comment by lukaszsamson** [comment] 2023-12-22 07:05
OTP 26.2.1 is out and with with fix for this issue

**Closed by lukaszsamson** 2023-12-22 07:05 UTC
Labels: waiting-on-upstream
