### ISSUE TITLE
Run tests without debugging

### ISSUE THREAD

**Issue by a3kov** [elixir-lsp/vscode-elixir-ls#323] opened 2023-04-20 09:25 UTC
I can run hundreds of tests with `mix test` in less than 1 second.
Yet it takes several minutes to do the same in VScode. Seems like the reason is it's using debug mode in tests ?
If somebody wants to debug a test case, they should be able to do that separately, probably while running a single test, not the whole suite. There should be a toggle somewhere I guess ? I don't know if this is possible, but we should not by default get worse DX compared to running mix in terminal.

**Comment by lukaszsamson** [comment] 2023-04-20 09:47
Duplicate of https://github.com/elixir-lsp/vscode-elixir-ls/issues/306

**Closed by lukaszsamson** 2023-04-20 09:47 UTC
