### ISSUE TITLE
Annoying red highlighting of the whole mix.exs

### ISSUE THREAD

**Issue by crabvk** [elixir-lsp/vscode-elixir-ls#132] opened 2020-08-13 07:22 UTC
If a project has problems with deps (or some other errors), the whole mix.exs is highlighted red. This is annoying and interferes with editing the file.
Is there an option to disable highlighting of mix.exs, or maybe highlight only the first line of it?

**Comment by wingyplus** [comment] 2020-08-15 13:31
Can you please copy the output from Output tab in vscode to this issue?

**Comment by vyachkonovalov** [comment] 2020-08-15 13:40
```log
Started ElixirLS v0.5.0
Elixir version: "1.10.4 (compiled with Erlang/OTP 23)"
Erlang version: "23"
ElixirLS compiled with Elixir 1.7.4 and erlang 20
MIX_ENV: test
MIX_TARGET: 
[Warn  - 6:38:06 PM] Unchecked dependencies for environment test:
[Warn  - 6:38:06 PM] * telemetry_metrics (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * phoenix_live_dashboard (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * ecto_sql (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * telemetry_poller (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * gettext (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * jason (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * phoenix_html (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * phoenix (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * postgrex (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * plug_cowboy (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"
[Warn  - 6:38:06 PM] * phoenix_ecto (Hex package)
[Warn  - 6:38:06 PM]   the dependency is not available, run "mix deps.get"

18:38:06.987 [error] Process #PID<0.126.0> raised an exception
** (Mix.Error) Can't continue due to errors on dependencies
    (mix 1.10.4) lib/mix.ex:392: Mix.raise/1
    (mix 1.10.4) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/tasks/loadpaths.ex:35: Mix.Tasks.Loadpaths.run/1
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/tasks/compile.ex:90: Mix.Tasks.Compile.run/1
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (language_server 0.5.0) lib/language_server/build.ex:204: ElixirLS.LanguageServer.Build.compile/0
```

**Comment by jameskentTX** [comment] 2020-08-20 05:39
I had the same problem. I deleted .elixir_ls directory and closed vscode.
It was ok when I opened editor next time.

**Comment by jameskentTX** [comment] 2020-08-20 08:37
I have the same problem with one specific project. Message says: Build failed for unknown reason. See output log.
I have installed ElixirLS 0.6.0-dev version, but it didn't help.

I don't think this is an error. The message clearly states: "build failed".
Other projects are ok.

**Comment by jameskentTX** [comment] 2020-08-20 11:12
I had the same problem when I updated few dependencies in original project from github. Red highlighting of the whole mix.exs is a result of problems with dependencies in your project.

**Comment by vyachkonovalov** [comment] 2020-08-26 08:51
@axelson 
I'm using vscode 1.48.2 with [JakeBecker.elixir-ls](https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls), what language server client am I using?

**Comment by cjbottaro** [comment] 2020-12-11 14:15
My mixfile (umbrella) is always covered in red. The problems tab seems to indicate it's a problem with elixir-ls.

```
an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.split/3
        (elixir 1.11.2) lib/string.ex:473: String.split(nil, ":", [])
        (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
        (stdlib 3.13.2) erl_eval.erl:888: :erl_eval.expr_list/6
        (stdlib 3.13.2) erl_eval.erl:411: :erl_eval.expr/5
        (stdlib 3.13.2) erl_eval.erl:449: :erl_eval.expr/5
        (elixir 1.11.2) src/elixir.erl:280: :elixir.recur_eval/3
        (elixir 1.11.2) src/elixir.erl:265: :elixir.eval_forms/3
        (elixir 1.11.2) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

![](http://storage.cjbotta.ro/20201211-081127.png)

**Comment by jjcarstens** [comment] 2020-12-11 17:44
FWIW, I find that this happens anytime I change a dependency in the `mix.exs` file (or add something that breaks it). It seems to get the build in a stuck state (as if cached and can't detect new changes past the error?).

Anyway, I can typically resolve by doing `rm -rf .elixir_ls/build` then reload the window (or manually save the file to trigger ElixirLS to run again)

**Comment by dsnipe** [comment] 2021-04-13 12:12
I have the same issue with the umbrella application. It happens every time when dependencies are changed, which can be quite often. 
@axelson Could you explain, please, a bit more how it could be related to an environment variable?

**Comment by dersmon** [comment] 2021-04-29 07:26
Same problem for me with an umbrella project.  Just a hunch: 

ElixirLS only checks the top-level mix.exs for dependeny changes in order to trigger updates to its internal book keeping concerning dependencies. So when you add a new dependency to one of your apps' mix.exs and install it, it fails to re-evaluate the umbrella project's deps directory.

@jjcarstens solution also works for me.

**Comment by ConnorRigby** [comment] 2021-05-20 20:01
bump

**Comment by lovebes** [comment] 2021-08-16 15:07
Question. Is there a way to introduce some environment variable during the `mix deps.get` that is being run whlie building out `.elixir_ls`? In my `config/config.exs` I have this:

`config :goth, json: System.get_env("GOOGLE_APPLICATION_CREDENTIALS") |> File.read!()`

.. and elixir-ls can't find the environment variable, because that is set via `direnv`.

If only I can run `direnv allow` in the terminal/shell session where elixirls is doing its thing, then it might work.

Else I might have to just conditionally `|> File.read!()` in the config.

**Comment by That-David-Guy** [comment] 2021-12-21 01:11
From here [https://github.com/JakeBecker/elixir-ls/issues/71#issuecomment-455335633](https://github.com/JakeBecker/elixir-ls/issues/71#issuecomment-455335633) :


> I was able to make this stop happening by changing 2 configuration settings in ElixirLS:
> 
> - uncheck Fetch Deps automatically option
> - changed Project Dir to . (it was empty and had a red error alert around it)
> 
> When I restarted VScode the issue was resolved.
> This does mean that you have to run mix deps.get and deps.compile manually when you make changes, but I kind of prefer that--I know the state of things in my conceptual understanding of my deps :)


This solved the issue for me

**Comment by rossvz** [comment] 2022-01-03 20:07
I tried the solution from @That-David-Guy which didn't seem to resolve. Manually removing the entire `.elixir_ls/build` directory occassionally does fix it for me, but with a large project and a number of dependencies it takes too long to recompile everything. At this point I just always expect the mix.exs file to be red constantly. Even going into that file to bump a version number results in the entire thing going red.

**Comment by cognivore** [comment] 2022-05-23 01:01
I wonder how to, in general, debug stuff like this.

I had ElixirLS completely broken for half an hour today, and then I did some random stuff and I fixed it. 

It seemed to have failed to parse mix credo output, which, I presume, was complaining about a crash, but I couldn't even see the whole log...

And of course, this UX peculiarity plagues my workflow as well.

**Comment by lukaszsamson** [comment] 2022-10-07 22:35
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/120

**Closed by lukaszsamson** 2022-10-07 22:35 UTC
Labels: duplicate
