### ISSUE TITLE
VS Code keeps notifying that "Elixir-LS has crashed"

### ISSUE THREAD

**Issue by mohan-win** [elixir-lsp/vscode-elixir-ls#261] opened 2022-08-10 07:10 UTC
### Environment

Most of this can be filled out by running the VSCode command (by default bound to Ctrl+Shift+P) "ElixirLS: Copy Debug Info"

- Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.0.3], Elixir (1.13.4)
- VSCode ElixirLS version: v0.10.0
- Operating System Version: M1 Max Mac OS Montery

### Crash report template

_Delete this section if not reporting a crash_

[exthost.log](https://github.com/elixir-lsp/vscode-elixir-ls/files/9297643/exthost.log)

Please check the above crash log..

**Comment by mohan-win** [comment] 2022-08-10 07:16
Attaching ElixirLS-Output during the crash..
[ElixirLS-Output.log](https://github.com/elixir-lsp/vscode-elixir-ls/files/9297696/ElixirLS-Output.log)

**Comment by lukaszsamson** [comment] 2022-08-25 17:56
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/696
Fixed in 0.11

**Closed by lukaszsamson** 2022-08-25 17:56 UTC
Labels: duplicate
