### ISSUE TITLE
Errors in all versions

### ISSUE THREAD

**Issue by niconsm16** [elixir-lsp/vscode-elixir-ls#333] opened 2023-05-25 13:45 UTC
[Trace - 10:43:49] Sending request 'initialize - (0)'.
Starting ElixirLS release v0.14.6
Running in c:/Workspaces/Elixir/learn
Error while loading project :elixir_ls at c:/Users/myuser/AppData/Local/mix/Cache/installs/elixir-1.13.0-erts-14.0/87e81e5daf685ed1bb3726eb2a9adf96/deps/elixir_ls
** (UndefinedFunctionError) function Code.Formatter.locals_without_parens/0 is undefined (module Code.Formatter is not available)
    (elixir 1.13.0) Code.Formatter.locals_without_parens()
    (elixir 1.13.0) lib/code/normalizer.ex:22: Code.Normalizer.normalize/2
    (elixir 1.13.0) lib/code.ex:1107: Code.quoted_to_algebra/2
    (elixir 1.13.0) lib/macro.ex:948: Macro.to_string/1
[Error - 10:43:52] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:43:52] Connection to server got closed. Server will restart.
true
[Error - 10:43:52] ElixirLS - learn client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 10:43:52] Sending request 'initialize - (0)'.

**Comment by lukaszsamson** [comment] 2023-05-25 14:39
Please post a project that reproduces it and fill the error template. Your elixir install looks broken

**Comment by lukaszsamson** [comment] 2023-06-12 09:53
Closing due to lack of OP's interest

**Closed** 2023-06-14 06:24 UTC
